import pallete1 from "@/public/pallete1.png";
import pallete2 from "@/public/pallete2.png";
import pallete3 from "@/public/pallete3.png";
import pallete4 from "@/public/pallete4.png";

export const Products = [
  {
    id: 1,
    name: "Design Your Own Pallete",
    label: "Now Available!",
    description: "",
    colors: "Variety of",
    price: "Starting from E£8999",
    image: pallete1,
  },
  {
    id: 2,
    name: "Metal Palletes",
    label: "New",
    description: "Ready-To-Go Palletes",
    colors: "4",
    price: "E£ 13999",
    image: pallete3,
  },
  {
    id: 3,
    name: "Plastic Palletes",
    label: "",
    description: "Rental Palletes",
    colors: 3,
    price: "E£ 12999",
    image: pallete1,
  },
  {
    id: 4,
    name: "Wood Palletes",
    label: "",
    description: "Customizable Palletes",
    colors: 2,
    price: "E£ 11999",
    image: pallete2,
  },
  {
    id: 5,
    name: "Aluminum Palletes",
    label: "Limited Edition",
    description: "Lightweight Palletes",
    colors: 6,
    price: "E£ 15999",
    image: pallete1,
  },
  {
    id: 6,
    name: "Steel Palletes",
    label: "New",
    description: "Heavy Duty Palletes",
    colors: 4,
    price: "E£ 16999",
    image: pallete3,
  },
  {
    id: 7,
    name: "Composite Palletes",
    label: "Sale",
    description: "Durable Palletes",
    colors: 3,
    price: "E£ 13999",
    image: pallete2,
  },
  {
    id: 8,
    name: "Cardboard Palletes",
    label: "",
    description: "Eco-Friendly Palletes",
    colors: 5,
    price: "E£ 10999",
    image: pallete4,
  },
  {
    id: 9,
    name: "Plastic Palletes",
    label: "Bestseller",
    description: "Rental Palletes",
    colors: 4,
    price: "E£ 12999",
    image: pallete1,
  },
  {
    id: 10,
    name: "Wood Palletes",
    label: "",
    description: "Customizable Palletes",
    colors: 2,
    price: "E£ 11999",
    image: pallete3,
  },
  {
    id: 11,
    name: "Plastic Palletes",
    label: "Bestseller",
    description: "Rental Palletes",
    colors: 5,
    price: "E£ 14999",
    image: pallete4,
  },
];
